export interface Product {
  name: string;
  price: number;
  originalPrice?: number;
  discount?: number;
}

export interface Category {
  slug: string;
  name: string;
  nameEn: string;
  icon: string;
  description: string;
  products: Product[];
}

export const categories: Category[] = [
  {
    slug: "shoes",
    name: "รองเท้าคอมแบท",
    nameEn: "Combat Boots",
    icon: "👟",
    description: "รองเท้าหนังวัวแท้ 100% พื้นยางพาราอย่างดี ทนทาน ใส่สบาย",
    products: [
      { name: "Bogie1 รองเท้าคอมแบท รุ่น E1", price: 1390, originalPrice: 1500, discount: 7 },
      { name: "Bogie1 รองเท้าคอมแบท รุ่น 9H", price: 1690, originalPrice: 1850, discount: 9 },
      { name: "Bogie1 รองเท้าคอมแบท รุ่น L02", price: 1700, originalPrice: 1850, discount: 8 },
      { name: "Bogie1 รองเท้าคอมแบท รุ่น J01", price: 1850, originalPrice: 2000, discount: 8 },
      { name: "Bogie1 รองเท้าตำรวจ รุ่น PS", price: 1290, originalPrice: 1390, discount: 7 },
      { name: "Bogie1 รองเท้าคอมแบท รุ่น A1", price: 1490, originalPrice: 1650, discount: 10 },
      { name: "Bogie1 รองเท้าคอมแบท รุ่น B1", price: 1590, originalPrice: 1750, discount: 9 },
      { name: "Bogie1 รองเท้าคอมแบท รุ่น C1", price: 1690, originalPrice: 1850, discount: 9 },
      { name: "Bogie1 รองเท้าคอมแบท Side Zip", price: 1890, originalPrice: 2100, discount: 10 },
      { name: "Bogie1 รองเท้าคอมแบท Low Cut", price: 1290, originalPrice: 1400, discount: 8 },
    ],
  },
  {
    slug: "armor",
    name: "เสื้อเกราะ",
    nameEn: "Tactical Vest / Body Armor",
    icon: "🦺",
    description: "เสื้อเกราะยุทธวิธี ระบบปลดเร็ว MOLLE compatible หลายรุ่นให้เลือก",
    products: [
      { name: "Bogie1 เสื้อเกราะปลดไว 4 จุด หัว Cobra รุ่น VORTEX-Z (VorZ)", price: 3900, originalPrice: 9000, discount: 57 },
      { name: "Bogie1 เสื้อเกราะปลดเร็ว รุ่น AHQ9 สีดำ", price: 1950, originalPrice: 3500, discount: 44 },
      { name: "Bogie1 เสื้อเกราะปลดเร็ว รุ่น AHQ9 สีเขียว", price: 1950, originalPrice: 3500, discount: 44 },
      { name: "Bogie1 เสื้อเกราะปลดเร็ว รุ่น AHQ7", price: 1750, originalPrice: 3200, discount: 45 },
      { name: "Bogie1 เสื้อเกราะปลดไว 4 จุด รุ่น AHQ12", price: 2500, originalPrice: 3900, discount: 36 },
      { name: "Bogie1 เสื้อเกราะ AHQ3 สีมัลติแคม", price: 4390, originalPrice: 4500, discount: 2 },
      { name: "Bogie1 เสื้อเกราะ รุ่น AHQ9 สีมัลติแคม", price: 2190, originalPrice: 3500, discount: 37 },
      { name: "Bogie1 เสื้อเกราะ รุ่น AHQ3-Grey (New Release)", price: 4390, originalPrice: 4500, discount: 2 },
      { name: "Bogie1 เสื้อเกราะ 3 แมก ปลดเร็ว (รุ่นใหม่)", price: 3750, originalPrice: 3900, discount: 4 },
      { name: "Bogie1 เสื้อเกราะ AHQ1", price: 3190, originalPrice: 3300, discount: 3 },
      { name: "Bogie1 เสื้อเกราะ AHQ2", price: 3190, originalPrice: 3300, discount: 3 },
      { name: "Bogie1 เสื้อเกราะ รุ่น AHQ3", price: 4390, originalPrice: 4500, discount: 2 },
      { name: "เสื้อเกราะ Bogie1 รุ่น AHQ4", price: 3690, originalPrice: 3800, discount: 3 },
      { name: "Bogie1 เสื้อเกราะปลดเร็ว รุ่น AHQ5", price: 2400, originalPrice: 2490, discount: 4 },
      { name: "Bogie1 เสื้อเกราะ 4 แม็ก", price: 3390, originalPrice: 3600, discount: 6 },
      { name: "Bogie1 แผ่นเปลี่ยนข้างเกราะ รุ่น V02", price: 790, originalPrice: 990, discount: 20 },
      { name: "Bogie1 เป้เกราะ", price: 3450, originalPrice: 3600, discount: 4 },
    ],
  },
  {
    slug: "pants",
    name: "กางเกงยุทธวิธี",
    nameEn: "Tactical Pants",
    icon: "👖",
    description: "กางเกงยุทธวิธี ทนทาน กระเป๋าหลายช่อง เหมาะทุกภารกิจ",
    products: [
      { name: "Bogie1 กางเกงยุทธวิธี รุ่น IX10", price: 1390, originalPrice: 1500, discount: 7 },
      { name: "Bogie1 กางเกงยุทธวิธี รุ่น IX12", price: 1490, originalPrice: 1650, discount: 10 },
      { name: "Bogie1 กางเกงยุทธวิธี รุ่น IX9", price: 1390, originalPrice: 1500, discount: 7 },
      { name: "Bogie1 กางเกงสนับเข่า Combat Pants", price: 1690, originalPrice: 1850, discount: 9 },
      { name: "Bogie1 กางเกงยุทธวิธี รุ่น IX15-PRO", price: 1650, originalPrice: 1800, discount: 8 },
      { name: "Bogie1 กางเกงยุทธวิธี รุ่น IX15 Pro Gen.2", price: 1690, originalPrice: 1850, discount: 9 },
      { name: "Bogie1 กางเกงขาสั้น IX10", price: 990, originalPrice: 1100, discount: 10 },
      { name: "Bogie1 กางเกงกีฬา ขาสั้น", price: 250 },
    ],
  },
  {
    slug: "belts",
    name: "เข็มขัดยุทธวิธี",
    nameEn: "Tactical Belts",
    icon: "🔗",
    description: "เข็มขัดยุทธวิธีหลายรุ่น ระบบ Cobra ทนทาน ใช้งานได้จริง",
    products: [
      { name: "Bogie1 เข็มขัดยุทธวิธี 2 ชั้น รุ่น PD25", price: 950, originalPrice: 1250, discount: 24 },
      { name: "Bogie1 เข็มขัดยุทธวิธี 2 ชั้น รุ่น PD23", price: 900, originalPrice: 950, discount: 5 },
      { name: "Bogie1 เข็มขัดยุทธวิธี Tactical Belt รุ่น cobra: PD22", price: 880, originalPrice: 950, discount: 7 },
      { name: "Bogie1 รวมชุดเซตอุปกรณ์ รอบเอว", price: 3330 },
      { name: "Bogie1 เข็มขัดสนาม 3 ชั้น รุ่น BELT-009", price: 1190, originalPrice: 1250, discount: 5 },
      { name: "Bogie1 เข็มขัดยุทธวิธี รุ่น 3 เส้น", price: 1190, originalPrice: 1250, discount: 5 },
      { name: "Bogie1 เข็มขัดสนามพร้อมรองนวม", price: 620, originalPrice: 650, discount: 5 },
      { name: "Bogie1 เข็มขัดสนาม", price: 420, originalPrice: 450, discount: 7 },
      { name: "Bogie1 เข็มขัดสนาม เข็มขัดยุทธวิธี รุ่น 2 ชั้น หัวล็อก 2 ชั้น", price: 950, originalPrice: 1050, discount: 10 },
      { name: "Bogie1 เข็มขัดยุทธวิธี Cobra PD21 (เส้นเดี่ยว)", price: 620, originalPrice: 650, discount: 5 },
      { name: "Bogie1 ชุดเข็มขัดประกอบเครื่องแบบ", price: 6250, originalPrice: 6400, discount: 2 },
      { name: "Bogie1 สายเก่ง สายโยง", price: 850 },
      { name: "Bogie1 เข็มขัดสนาม Battle Belt รุ่น ECO", price: 350 },
      { name: "Bogie1 เข็มขัดยุทธวิธี สายบาง", price: 320, originalPrice: 350, discount: 9 },
      { name: "Bogie1 เข็มขัดปลดเร็ว PD20", price: 320, originalPrice: 350, discount: 9 },
      { name: "Bogie1 เข็มขัด 2 หน้า", price: 330, originalPrice: 350, discount: 6 },
      { name: "Bogie1 เข็มขัดยุทธวิธี CQB", price: 350 },
      { name: "Bogie1 เข็มขัด PD18", price: 450 },
    ],
  },
  {
    slug: "holsters",
    name: "ซองปืน-ซองแม็ก",
    nameEn: "Holsters & Mag Pouches",
    icon: "🔫",
    description: "ซองปืนโพลิเมอร์ ซองแม็ก เพลทเหน็บ รองรับปืนหลายรุ่น",
    products: [
      { name: "Bogie1 ซองปืนโพลิเมอร์ G17-G19-P320 รุ่น FR", price: 3500, originalPrice: 4500, discount: 22 },
      { name: "Bogie1 ซองปืนปิดศูนย์หลัง Glock19 (Level3)", price: 1250, originalPrice: 1500, discount: 17 },
      { name: "Bogie1 ซองปืน Sig P320 (ปลดล็อกด้วยนิ้วโป้ง)", price: 1100, originalPrice: 1500, discount: 27 },
      { name: "Bogie1 ซองปืนโพลิเมอร์ P320", price: 800, originalPrice: 850, discount: 6 },
      { name: "ซองปืนโพลิเมอร์ Bogie1 CZ - Glock - 1911 - SigP320", price: 800, originalPrice: 850, discount: 6 },
      { name: "Bogie1 ซองปืนโพลิเมอร์ CZ-Compact", price: 800, originalPrice: 850, discount: 6 },
      { name: "Bogie1 ซองแมกคู่ S.V2", price: 800, originalPrice: 850, discount: 6 },
      { name: "Bogie1 ซองแมกกาซีน ชนิดเดี่ยว รุ่น V2", price: 690, originalPrice: 750, discount: 8 },
      { name: "Bogie1 ซองแมก + ซองไฟฉาย รุ่น V7", price: 990, originalPrice: 1050, discount: 6 },
      { name: "Bogie1 ซองแมกคู่ ปืนสั้น รุ่น V2", price: 850, originalPrice: 990, discount: 14 },
      { name: "Bogie1 ซองแมกกาซีน 2 ชั้น", price: 800, originalPrice: 850, discount: 6 },
      { name: "Bogie1 ซองแมกเดี่ยว M16 V.2", price: 550 },
      { name: "Bogie1 ซองปืนหนังพกใน Sig P365 / Sig P320", price: 390, originalPrice: 450, discount: 13 },
      { name: "Bogie1 รวมรุ่น ซองปืนหนังพกใน Glock - Sig - CZ - Beretta", price: 390, originalPrice: 450, discount: 13 },
      { name: "ซองปืนหนังพกใน Bogie1", price: 450 },
      { name: "Bogie1 ซองปืนโพลิเมอร์ CZ75/B Compact", price: 800, originalPrice: 850, discount: 6 },
      { name: "Bogie1 ซองปืนโพลิเมอร์ Glock17", price: 800, originalPrice: 850, discount: 6 },
      { name: "Bogie1 ซองปืนโพลิเมอร์ 1911 (3/4/5 นิ้ว)", price: 800, originalPrice: 850, discount: 6 },
      { name: "Bogie1 ซองปืนโพลิเมอร์ CZ75-SP01-Shadow", price: 800, originalPrice: 850, discount: 6 },
      { name: "Bogie1 ซองปืนโพลิเมอร์ Glock26", price: 800, originalPrice: 850, discount: 6 },
    ],
  },
  {
    slug: "conceal-bags",
    name: "กระเป๋าซ่อนปืน",
    nameEn: "Concealed Carry Bags",
    icon: "👜",
    description: "กระเป๋าซ่อนปืนหลายทรง คาดเอว สะพายข้าง ร้อยเข็มขัด",
    products: [
      { name: "กระเป๋าซ่อนปืน สี่เหลี่ยม", price: 820, originalPrice: 950, discount: 14 },
      { name: "Bogie1 กระเป๋าซ่อนปืน ทรงสี่เหลี่ยม ซิปกันน้ำ", price: 920, originalPrice: 1000, discount: 8 },
      { name: "กระเป๋าซ่อนปืนพกใน Bogie1", price: 790, originalPrice: 890, discount: 11 },
      { name: "กระเป๋าซ่อนปืนคาดเอว รุ่น Strap", price: 1090, originalPrice: 1250, discount: 13 },
      { name: "กระเป๋าซ่อนปืน สามเหลี่ยม Bogie1", price: 850, originalPrice: 1000, discount: 15 },
      { name: "กระเป๋าคาดเอว Bogie1", price: 620, originalPrice: 650, discount: 5 },
      { name: "กระเป๋าซ่อนปืน รุ่น Strap ร้อยเข็มขัด", price: 620, originalPrice: 650, discount: 5 },
      { name: "Bogie1 กระเป๋าซ่อนปืน ร้อยเข็มขัด V2", price: 620, originalPrice: 650, discount: 5 },
      { name: "Bogie1 กระเป๋าเก็บปืน", price: 450, originalPrice: 500, discount: 10 },
      { name: "กระเป๋าเก็บปืน Bogie1", price: 460, originalPrice: 500, discount: 8 },
      { name: "กระเป๋าคาดเอวรัดขา Bogie1", price: 1100 },
      { name: "กระเป๋าซ่อนปืน T1", price: 1090 },
      { name: "Bogie1 กระเป๋าร้อยเข็มขัด", price: 550, originalPrice: 600, discount: 8 },
    ],
  },
  {
    slug: "backpacks",
    name: "เป้-กระเป๋าสะพาย",
    nameEn: "Backpacks & Bags",
    icon: "🎒",
    description: "เป้ยุทธวิธี กระเป๋าสะพาย MOLLE compatible วัสดุ Cordura อย่างดี",
    products: [
      { name: "Bogie1 กระเป๋าสะพายข้าง Slide Bag", price: 1890, originalPrice: 2250, discount: 16 },
      { name: "กระเป๋าปืนทรงก้ามปู", price: 1180, originalPrice: 1250, discount: 6 },
      { name: "กระเป๋าสะพายข้าง B2C", price: 1180, originalPrice: 1300, discount: 9 },
      { name: "Bogie1 กระเป๋า Banger Bag", price: 1290, originalPrice: 1350, discount: 4 },
      { name: "กระเป๋าสะพายหน้า ซ่อนปืน Bogie1", price: 790, originalPrice: 850, discount: 7 },
      { name: "เป้ ใส่ปืน สะพายหน้า Bogie1", price: 720, originalPrice: 750, discount: 4 },
      { name: "กระเป๋าสะพายข้าง สามเหลี่ยมซ่อนปืน Bogie1", price: 1250 },
      { name: "Bogie1 กระเป๋าสะพายข้าง รุ่น 3 แมก", price: 1250, originalPrice: 1350, discount: 7 },
      { name: "กระเป๋าใส่ปืนสะพายไขว้ Bogie1", price: 1190, originalPrice: 1250, discount: 5 },
      { name: "Bogie1 กระเป๋าเป้ สะพายหลัง รุ่น RIGGER BACKPACK (43L)", price: 1710, originalPrice: 1800, discount: 5 },
      { name: "Bogie1 เป้ 3P", price: 890 },
      { name: "Bogie1 เป้ 3P Pro", price: 1190, originalPrice: 1250, discount: 5 },
      { name: "เป้ - แม่ลูก Bogie1", price: 1300 },
      { name: "Bogie1 เป้ SMC (18L)", price: 1250 },
      { name: "Bogie1 กระเป๋า Gepäck M16 (43L)", price: 4290 },
      { name: "Bogie1 กระเป๋าสัมภาระ 65L (ถุงทะเล) ผ้าคอดูร่า", price: 2650 },
      { name: "Bogie1 กระเป๋าสะพายข้างสี่เหลี่ยม", price: 850 },
      { name: "Bogie1 เป้ 3D", price: 1700, originalPrice: 1800, discount: 6 },
    ],
  },
  {
    slug: "shirts",
    name: "เสื้อยืด-โปโล",
    nameEn: "T-Shirts & Polo",
    icon: "👕",
    description: "เสื้อยืด เสื้อโปโล Combat Shirt ผ้าระบายอากาศ เหมาะชุดฝึก",
    products: [
      { name: "Bogie1 เสื้อโปโล", price: 690, originalPrice: 750, discount: 8 },
      { name: "Bogie1 เสื้อคอมแบทเชิ้ต Gen2", price: 1200, originalPrice: 1250, discount: 4 },
      { name: "Bogie1 เสื้อคอมแบทเชิ้ต Gen2 แขนสั้น", price: 1200, originalPrice: 1250, discount: 4 },
      { name: "Bogie1 เสื้อโปโล Gen2", price: 730, originalPrice: 750, discount: 3 },
      { name: "Bogie1 เสื้อเชิ้ต VIP แขนสั้น", price: 1150 },
      { name: "Bogie1 เสื้อนาโน คอกลม", price: 330, originalPrice: 350, discount: 6 },
      { name: "Bogie1 เสื้อนาโน ตรา ทบ.", price: 330, originalPrice: 350, discount: 6 },
      { name: "Bogie1 เสื้อนาโน คอวี", price: 330, originalPrice: 350, discount: 6 },
      { name: "Bogie1 เสื้อนาโน คอกลม (หนา)", price: 520, originalPrice: 550, discount: 5 },
      { name: "Bogie1 เสื้อคอกลม แขนยาว", price: 430, originalPrice: 450, discount: 4 },
      { name: "Bogie1 เสื้อ คอเต่า สีดำ", price: 350 },
      { name: "Bogie1 เสื้อคอแหลม แขนยาว Royal Thai Police", price: 320, originalPrice: 350, discount: 9 },
    ],
  },
  {
    slug: "vests",
    name: "เสื้อกั๊ก-ชุดเวส",
    nameEn: "Vests & Duty Wear",
    icon: "🦺",
    description: "เสื้อกั๊กตำรวจ สะท้อนแสง ชุดเวสฝึก ชุด คฝ. หลายแบบ",
    products: [
      { name: "Bogie1 เสื้อกั๊กสะท้อนแสง รุ่นใหม่", price: 550, originalPrice: 650, discount: 15 },
      { name: "Bogie1 เสื้อกั๊ก POLICE รุ่นใหม่ ถูกระเบียบ", price: 630, originalPrice: 650, discount: 3 },
      { name: "Bogie1 เสื้อกั๊กตำรวจ สะท้อนแสง", price: 630, originalPrice: 650, discount: 3 },
      { name: "Bogie1 เสื้อกั๊กตำรวจ ติดเครื่องหมาย", price: 530, originalPrice: 550, discount: 4 },
      { name: "Bogie1 เสื้อกั๊ก สีกรม มีแถบสะท้อนแสง", price: 630, originalPrice: 650, discount: 3 },
      { name: "Bogie1 เสื้อกั๊ก สีกรม ไม่มีแถบสะท้อนแสง", price: 530, originalPrice: 550, discount: 4 },
      { name: "Bogie1 เสื้อกั๊กกรมการปกครอง สีกรม คอปก รุ่นมีตีนตุ๊กแก", price: 630, originalPrice: 650, discount: 3 },
      { name: "Bogie1 เสื้อกั๊กกรมการปกครอง คอปก (ไม่มีตีนตุ๊กแก)", price: 630, originalPrice: 650, discount: 3 },
      { name: "Bogie1 เสื้อกั๊กมีแถบสะท้อนแสง คอปก สีดำ", price: 630, originalPrice: 650, discount: 3 },
      { name: "Bogie1 เสื้อกั๊ก คอปก สีดำ", price: 530, originalPrice: 550, discount: 4 },
      { name: "Bogie1 เสื้อกั๊ก สนว. มีแถบสะท้อนแสง", price: 630, originalPrice: 650, discount: 3 },
      { name: "Bogie1 เสื้อกั๊ก สนว. ไม่มีแถบสะท้อนแสง", price: 530, originalPrice: 550, discount: 4 },
      { name: "Bogie1 เสื้อกั๊ก รุ่น VIP Vest", price: 1420, originalPrice: 1500, discount: 5 },
      { name: "Bogie1 เสื้อกั๊ก Tactical (นักข่าว)", price: 1450, originalPrice: 1490, discount: 3 },
      { name: "Bogie1 ชุดเวส ชุดฝึก ชุด คฝ. (รุ่นใหม่)", price: 1700, originalPrice: 1850, discount: 8 },
      { name: "Bogie1 ชุดเวส/ชุดฝึก/ชุดคฝ/ชุดปจ", price: 1700, originalPrice: 1850, discount: 8 },
      { name: "Bogie1 เสื้อกั๊กวิทยุ", price: 550 },
    ],
  },
  {
    slug: "armor-accessories",
    name: "อุปกรณ์ติดเสื้อเกราะ",
    nameEn: "Armor Accessories",
    icon: "⚙️",
    description: "ซองแมก กระเป๋าเอนกประสงค์ เพลท ซองวิทยุ สำหรับติดเสื้อเกราะ",
    products: [
      { name: "Bogie1 ซองแมกเดี่ยว M16 (Ver2)", price: 800, originalPrice: 850, discount: 6 },
      { name: "Bogie1 ซองแมกกาซีน 2 ชั้น", price: 800, originalPrice: 850, discount: 6 },
      { name: "Bogie1 กระเป๋าเอนกประสงค์ พร้อม ซองแมก สำหรับติดเสริมเสื้อเกราะ", price: 790, originalPrice: 850, discount: 7 },
      { name: "Bogie1 เพลทเอนกประสงค์ ติดเสื้อเกราะ", price: 620, originalPrice: 650, discount: 5 },
      { name: "Bogie1 ซองวิทยุติดเกราะ", price: 820, originalPrice: 850, discount: 4 },
      { name: "Bogie1 ซองปืนติดเกราะ", price: 820, originalPrice: 850, discount: 4 },
      { name: "Bogie1 กระเป๋ายา", price: 600, originalPrice: 650, discount: 8 },
      { name: "Bogie1 ซองแมก+ลูกซอง", price: 650 },
      { name: "Bogie1 ซองแมกเดี่ยว M16 ผ้าคอร์ดูร่า", price: 390, originalPrice: 450, discount: 13 },
      { name: "Bogie1 แผ่นข้างเสื้อเกราะ (Armor Removable quick-release side plates)", price: 790, originalPrice: 850, discount: 7 },
      { name: "Bogie1 เพลทติดเกราะ (ก้ามปู)", price: 650 },
      { name: "Bogie1 กระเป๋าเอนกประสงค์", price: 650 },
      { name: "Bogie1 กระเป๋าพยาบาล", price: 600, originalPrice: 650, discount: 8 },
      { name: "Bogie1 กระเป๋าเอนกประสงค์ (V2)", price: 650 },
      { name: "Bogie1 กระเป๋าน้ำ", price: 850 },
      { name: "Bogie1 เป้น้ำ", price: 1250, originalPrice: 1350, discount: 7 },
      { name: "Bogie1 ซองแมกปืนสั้นติดเกราะ (2 แมก)", price: 650 },
      { name: "Bogie1 กระเป๋าลูกระเบิด", price: 450 },
      { name: "Bogie1 กระเป๋าเป้ ติดเสื้อเกราะ", price: 1350 },
    ],
  },
  {
    slug: "jackets",
    name: "แจ็กเก็ต",
    nameEn: "Jackets",
    icon: "🧥",
    description: "แจ็กเก็ตยุทธวิธี กันลม สะท้อนแสง FBI Flight Jacket",
    products: [
      { name: "Bogie1 เสื้อแจ็คเก็ต FBI", price: 1750, originalPrice: 1890, discount: 7 },
      { name: "Bogie1 เสื้อแจ็กเก็ต JKT H01", price: 1790, originalPrice: 1850, discount: 3 },
      { name: "Bogie1 ชุดวอร์ม ตำรวจ", price: 1500 },
      { name: "Bogie1 แจ็กเก็ตสะท้อนแสง", price: 1650, originalPrice: 1850, discount: 11 },
      { name: "Bogie1 เสื้อแจ็กเก็ต กันลม", price: 1499 },
      { name: "Bogie1 แจ็กเก็ต TAD", price: 1790 },
      { name: "Bogie1 แจ็กเก็ตกระดุม", price: 2190 },
      { name: "Bogie1 Flight Jacket (ไฟล์ทแจ็กเก็ต)", price: 2199 },
    ],
  },
  {
    slug: "accessories",
    name: "สินค้าอื่นๆ",
    nameEn: "Accessories & Equipment",
    icon: "🔦",
    description: "ซองไฟฉาย หมวก FAST ดิ้ว ไฟฉาย ซองวิทยุ และอุปกรณ์เสริมอื่นๆ",
    products: [
      { name: "Bogie1 ซองไฟฉายโพลิเมอร์ Lock 360", price: 990, originalPrice: 1050, discount: 6 },
      { name: "Bogie1 ซองไฟฉาย โพลิเมอร์ รุ่น V7", price: 750, originalPrice: 890, discount: 16 },
      { name: "Bogie1 ซองไฟฉาย-ดิ้ว 360 องศา", price: 700, originalPrice: 750, discount: 7 },
      { name: "Bogie1 ซองกุญแจมือโพลิเมอร์ รุ่น 360", price: 990, originalPrice: 1050, discount: 6 },
      { name: "Bogie1 ซองกุญแจมือโพลิเมอร์", price: 820, originalPrice: 850, discount: 4 },
      { name: "Bogie1 ดิ้ว 21 นิ้ว พร้อมซองโพลิเมอร์", price: 1450, originalPrice: 1500, discount: 3 },
      { name: "Bogie1 ดิ้ว 24 นิ้ว พร้อมซองโพลิเมอร์ รุ่น Lock", price: 2150, originalPrice: 2200, discount: 2 },
      { name: "Bogie1 ดิ้ว 24 นิ้ว พร้อมซองโพลิเมอร์ หมุนได้ 360 องศา", price: 1750, originalPrice: 1900, discount: 8 },
      { name: "Bogie1 ดิ้ว 16 นิ้ว รุ่น Lock พร้อมซองโพลิเมอร์", price: 2150, originalPrice: 2200, discount: 2 },
      { name: "Bogie1 ดิ้ว 24 นิ้ว / 16 นิ้ว ยางหุ้มด้ามจับ", price: 1850, originalPrice: 1900, discount: 3 },
      { name: "Bogie1 หมวกฟาส FAST จราจร สีขาว-แดง", price: 1750 },
      { name: "Bogie1 หมวก FAST สีทอง-ดำ", price: 1750, originalPrice: 2200, discount: 20 },
      { name: "Bogie1 หมวก FAST สีดำ", price: 1750, originalPrice: 2200, discount: 20 },
      { name: "Bogie1 ไฟฉาย LED รุ่น T12-A", price: 1100, originalPrice: 1200, discount: 8 },
      { name: "Bogie1 ไฟฉาย LED Cree", price: 920, originalPrice: 950, discount: 3 },
      { name: "Bogie1 ไฟฉาย Ultra Fire", price: 450 },
      { name: "Bogie1 ซองใส่โทรศัพท์ 2 ช่อง", price: 620, originalPrice: 650, discount: 5 },
      { name: "Bogie1 ซองโทรศัพท์ 2 ช่อง สี Multicam Black", price: 620, originalPrice: 750, discount: 17 },
      { name: "Bogie1 ซองวิทยุ ผ้าคอร์ดูร่า รุ่น V.2 สี Multicam-Black", price: 850, originalPrice: 950, discount: 11 },
      { name: "Bogie1 ซองวิทยุปรับขนาดได้ (ผ้าคอร์ดูร่า)", price: 820, originalPrice: 850, discount: 4 },
      { name: "Bogie1 ซองวิทยุ ผ้า", price: 220 },
      { name: "Bogie1 ซองวิทยุ", price: 220 },
      { name: "Bogie1 ซองกุญแจมือ-ผ้า", price: 220 },
    ],
  },
];

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug);
}
